export interface Item {
  created?: string | null,
  description: string,
  difficulty?: string,
  difficultyCategoryId?: number,
  id: number,
  image?: string | null,
  name: string,
  position?: number,
  quantity?: number,
  tradelist?: boolean,
  tradelistQuantity?: number,
  unique?: boolean,
  updated?: string,
  wishlist?: boolean,
  wishlistQuantity?: number,
}
